# Generated by Django 4.1.1 on 2024-11-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='finished_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
